/**
 ******************************************************************************
 * @file    nextion_driver.c
 * @author  Generated by audit tool
 * @brief   Nextion HMI Driver Implementation (Stub)
 * @date    2025
 ******************************************************************************
 */

#include "nextion_driver.h"
#include "usart.h"
#include <string.h>
#include <stdio.h>

/* Private defines -----------------------------------------------------------*/
#define NEXTION_END_STRING "\xFF\xFF\xFF"
#define NEXTION_TIMEOUT_MS 100

/* Private variables ---------------------------------------------------------*/
static char nextion_buffer[128];

/* Function implementations --------------------------------------------------*/

/**
 * @brief Send a command to the Nextion display
 * @param command Command string to send
 */
void NEXTION_SendCommand(const char* command)
{
    if (command == NULL) return;
    
    // Clear buffer
    memset(nextion_buffer, 0, sizeof(nextion_buffer));
    
    // Prepare command with terminators
    snprintf(nextion_buffer, sizeof(nextion_buffer) - 4, "%s", command);
    strcat(nextion_buffer, NEXTION_END_STRING);
    
    // Send via UART1 
    HAL_UART_Transmit(&huart1, (uint8_t*)nextion_buffer, strlen(nextion_buffer), NEXTION_TIMEOUT_MS);
    
    // Wait for acknowledgment
    NEXTION_WaitForACK();
}

/**
 * @brief Wait for ACK from Nextion display
 */
void NEXTION_WaitForACK(void)
{
    uint8_t ack_buffer[4];
    uint32_t start_time = HAL_GetTick();
    
    // Wait for ACK (0x01 0xFF 0xFF 0xFF) with timeout
    while ((HAL_GetTick() - start_time) < NEXTION_TIMEOUT_MS) {
        if (HAL_UART_Receive(&huart1, ack_buffer, 4, 1) == HAL_OK) {
            if (ack_buffer[0] == 0x01 && ack_buffer[1] == 0xFF && 
                ack_buffer[2] == 0xFF && ack_buffer[3] == 0xFF) {
                return; // ACK received
            }
        }
    }
    // Timeout occurred, continue anyway
}

/**
 * @brief Set text of a Nextion object
 * @param object_name Name of the object
 * @param text Text to set
 */
void NEXTION_SetText(const char* object_name, const char* text)
{
    if (object_name == NULL || text == NULL) return;
    
    snprintf(nextion_buffer, sizeof(nextion_buffer), "%s.txt=\"%s\"", object_name, text);
    NEXTION_SendCommand(nextion_buffer);
}

/**
 * @brief Set value of a Nextion object
 * @param object_name Name of the object
 * @param value Value to set
 */
void NEXTION_SetValue(const char* object_name, int value)
{
    if (object_name == NULL) return;
    
    snprintf(nextion_buffer, sizeof(nextion_buffer), "%s.val=%d", object_name, value);
    NEXTION_SendCommand(nextion_buffer);
}

/**
 * @brief Set background color of a Nextion object
 * @param object_name Name of the object
 * @param color Color value (16-bit RGB565)
 */
void NEXTION_SetBackgroundColor(const char* object_name, uint32_t color)
{
    if (object_name == NULL) return;
    
    snprintf(nextion_buffer, sizeof(nextion_buffer), "%s.bco=%u", object_name, (unsigned int)color);
    NEXTION_SendCommand(nextion_buffer);
}

/**
 * @brief Set picture of a Nextion object
 * @param object_name Name of the object
 * @param pic_id Picture ID
 */
void NEXTION_SetPicture(const char* object_name, int pic_id)
{
    if (object_name == NULL) return;
    
    snprintf(nextion_buffer, sizeof(nextion_buffer), "%s.pic=%d", object_name, pic_id);
    NEXTION_SendCommand(nextion_buffer);
}

/**
 * @brief Change to a specific page
 * @param page Page number
 */
void NEXTION_ChangePage(uint8_t page)
{
    snprintf(nextion_buffer, sizeof(nextion_buffer), "page %d", page);
    NEXTION_SendCommand(nextion_buffer);
}